name: CI
on:
    push:
    pull_request:
    schedule:
        - cron: "0 0 * * 1"
env:
    CARGO_TERM_COLOR: always
    ISPC_VERSION: 1.25.3
jobs:
    build_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - run: curl -L https://github.com/ispc/ispc/releases/download/v$ISPC_VERSION/ispc-v$ISPC_VERSION-linux.tar.gz | tar xzv ispc-v$ISPC_VERSION-linux/bin/ispc
            - run: realpath "ispc-v$ISPC_VERSION-linux/bin/" >> $GITHUB_PATH
            - run: cargo build --all --all-targets --features ispc
            - run: cargo clippy --all --all-targets --features ispc -- -D warnings
            - run: cargo test --all
            - run: cargo doc --all --no-deps --document-private-items --all-features
              env:
                  RUSTDOCFLAGS: -Dwarnings
            - name: Format Core
              run: cargo fmt -- --check
    build_mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v5
            - name: Prepare Environment
              run: |
                curl -L https://github.com/ispc/ispc/releases/download/v$ISPC_VERSION/ispc-v$ISPC_VERSION-macOS.universal.tar.gz | tar xzv ispc-v$ISPC_VERSION-macOS.universal/bin/ispc
                echo "$PWD/ispc-v$ISPC_VERSION-macOS.universal/bin/" >> $GITHUB_PATH
            - run: cargo build --all --all-targets --features ispc
            - run: cargo clippy --all --all-targets --features ispc -- -D warnings
            - run: cargo test --all
    build_windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v5
            - run: |
                  curl -LO https://github.com/ispc/ispc/releases/download/v$env:ISPC_VERSION/ispc-v$env:ISPC_VERSION-windows.zip
                  unzip ispc-v$env:ISPC_VERSION-windows.zip ispc-v$env:ISPC_VERSION-windows/bin/ispc.exe
                  Resolve-Path "ispc-v$env:ISPC_VERSION-windows/bin" | Add-Content -Path $env:GITHUB_PATH
            - run: cargo build --all --all-targets --features ispc
            - run: cargo clippy --all --all-targets --features ispc -- -D warnings
            - run: cargo test --all
